baseURL = "https://developers.cloudflare.com"

title = "Cloudflare Docs"
languageCode = "en"
DefaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableRobotsTXT = false
summaryLength = 30
disableAliases = true
disableKinds = ["taxonomy", "taxonomyTerm"]

enableEmoji = true
enableGitInfo = true

paginate = 12 # default 10
paginatePath = "page" # default

#Â Coveo is a search solution - the following read-only token is used from the frontend to execute search queries
[params.coveo]
org = "cloudflareproduction7iy98g48"
token = "xx2b20a6dc-ce86-41cb-ad18-90bd2568dcdb"
tutorial_token = "xxa5a7d4c9-db72-424d-860d-ae68ff7f60ac"

[outputs]
  home = ['html', 'dash-sidebar']
  page = ['html', 'dash-sidebar']
  section = ['html', 'dash-sidebar']

[outputFormats]
  [outputFormats.DashSidebar]
    name = 'dash-sidebar'
    mediaType = 'text/html'
    path = '_docs-dash-sidebar'
    isHTML = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
	[markup.highlight]
		tabWidth = 2
		style = "github"
		codeFences = true
		guessSyntax = true
		lineNumbersInTable = true
		noClasses = false
		lineNoStart = 1
		lineNos = false
		hl_Lines = ""

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^CF_PAGES_BRANCH$']

[build]
  noJSConfigInAssets = true

[caches]
  [caches.getjson]
    maxAge = "24h"
