baseURL = "https://developers.cloudflare.com"

title = "Cloudflare Developers"
languageCode = "en"
DefaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableRobotsTXT = true

disableAliases = true
disableKinds = ["taxonomy", "taxonomyTerm"]

enableEmoji = true
enableGitInfo = true

# TODO
rssLimit = 10

paginate = 12 # default 10
paginatePath = "page" # default

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.7

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
	[markup.highlight]
		tabWidth = 2
		style = "github"
		codeFences = true
		guessSyntax = true
		lineNumbersInTable = true
		noClasses = false
		lineNoStart = 1
		lineNos = false
		hl_Lines = ""
