name = "images"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true
# Opt into backwards-incompatible changes through September 17, 2021.
compatibility_date = "2021-09-17"

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/images*"
kv_namespaces = [{ binding = "REDIRECTS", id = "0821ddd66f4742bdbbb56593b8b43fd8", preview_id = "0821ddd66f4742bdbbb56593b8b43fd8" }]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
