name = "rules"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/rules*"

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
