name = "magic-wan"
type = "webpack"
workers_dev = true
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/magic-wan*"
kv_namespaces = [
  { binding = "REDIRECTS", id = "3df92568465a4a0182d8b3fbd96236a5" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
