name = "warp-client"
type = "webpack"
account_id = "b54f07a6c269ecca2fa60f1ae4920c99" # cloudflare-docs.workers.dev
workers_dev = true

[env.production]
workers_dev = false
account_id = "b54f07a6c269ecca2fa60f1ae4920c99"
zone_id = "351cf9fc660523187714fa772ad5ca49"
route = "https://developers.cloudflare.com/warp-client*"
kv_namespaces = [ 
  { binding = "REDIRECTS", id = "f28bd6bb32a84aa0b4827c5dc2466bc1" }
]

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
