name: Accessibility Audits

on: 
  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install required Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libgbm-dev
          sudo apt-get install xvfb
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1
      - name: Install npm packages
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.0'
          extended: true

      - name: (env) pnpm
        run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

      - run: pnpm install
      - run: make build
          env:
            NODE_OPTIONS: "--max-old-space-size=8192"
      - name: Accessibility Audits
        run: |
          npm install -g @jakepartusch/lumberjack
          xvfb-run --auto-servernum lumberjack --url https://developers.cloudflare.com
