name: Begin Algolia crawl

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  crawl:
    name: Crawl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run script
        run: npm run algolia-crawl
        env:
          ALGOLIA_CRAWLER_API_KEY: ${{secrets.ALGOLIA_CRAWLER_API_KEY}}
          ALGOLIA_CRAWLER_ID: ${{secrets.ALGOLIA_CRAWLER_ID}}
          ALGOLIA_CRAWLER_URL: ${{secrets.ALGOLIA_CRAWLER_URL}}
          ALGOLIA_CRAWLER_USER_ID: ${{secrets.ALGOLIA_CRAWLER_USER_ID}}

