name: Crawl API docs links

on:
  pull_request:
    branches:
      - production

jobs:
  compile:
    name: Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1
      
      - name: Install @actions/core
        run: npm install @actions/core

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run API docs link checker
        id: check-api-links
        run: npm run crawl-api-links

      - name: Create issue
        env:
          EXPORTED_VARIABLE: ${{ steps.check-api-links.outputs.brokenLinks }}
        if: env.EXPORTED_VARIABLE
        run: |
          # Create the issue and reference the exported variable
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/cloudflare/cloudflare-docs/issues" \
            -d "{\"title\": \"Broken API docs links\", \"body\": \"TEST\", \"assignees\": [\"kodster28\"]}"

            

