name: CI

on:
  pull_request:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: (env) pnpm
        run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

      - run: pnpm install

      - run: make build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Check - Broken Links
        run: pnpm run crawl
        if: success()

      - name: Check - Infinite redirects
        run: npx tsm bin/find-infinite-redirects.ts

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: (env) pnpm
  #       run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
  #     - run: pnpm install
  #     - run: pnpm run lint
