name: PR Opened

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
on:
  pull_request_target:
    types: [opened, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Update assignees
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/assign-pr
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
