on:
  push:
    branches-ignore:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    name: Publish Preview
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - run: npm ci
      - uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/.astro
          key: static
      - run: npm run build
        name: Build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      - run: npx wrangler pages deploy --project-name cloudflare-docs dist
        name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - run: npx wrangler versions upload -c ./wrangler-workers.toml
        name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - uses: actions/cache/save@v4
        if: always()
        with:
          path: |
            node_modules/.astro
          key: static
